'use strict';
const {revealBriefControl}=require('./brief-ui-helpers.cjs');
// Optional integration smoke: BROWSER_PATH=/path/to/chromium node tests/ui-smoke.cjs
const {chromium}=require('../vendor/html-explainer/node/node_modules/playwright-core');
const {spawn,spawnSync}=require('child_process'),fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert');
(async()=>{const root=path.resolve(__dirname,'..'),workspace=fs.mkdtempSync(path.join(os.tmpdir(),'studio-ui-'));const port=18765,server=spawn(process.env.PYTHON||'python',['-m','app.server','--workspace',workspace,'--port',String(port)],{cwd:root,stdio:'ignore'});let browser;
try{for(let i=0;i<50;i++){try{if((await fetch(`http://127.0.0.1:${port}/api/health`)).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--single-process']});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${port}`);await page.waitForFunction(()=>document.querySelector('#stageTitle').textContent);
await revealBriefControl(page, '#editor'); await page.locator('#editor').fill('Explain how evidence classifications differ from risk magnitude.');await revealBriefControl(page, '#aspect'); await page.locator('#aspect').selectOption('9:16');await revealBriefControl(page, '#save'); await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已保存'));await revealBriefControl(page, '#editor'); await page.locator('#editor').fill('UNSAVED INPUT');assert.equal(await page.locator('#editor').inputValue(),'UNSAVED INPUT');
await revealBriefControl(page, '#continue'); await page.locator('#continue').click();await page.waitForFunction(()=>document.querySelector('#stageTitle').textContent==='文案');
await revealBriefControl(page, '#editor'); await page.locator('#editor').fill('Local dirty text');const doc=path.join(workspace,'external.md');fs.writeFileSync(doc,'External update');const result=spawnSync(process.env.PYTHON||'python',['-m','app.cli','--workspace',workspace,'save','--stage','narration','--file',doc],{cwd:root});assert.equal(result.status,0);await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('未保存文字'),{timeout:10000});assert.equal(await page.locator('#editor').inputValue(),'Local dirty text');page.once('dialog',d=>d.accept());await revealBriefControl(page, '#refresh'); await page.locator('#refresh').click();await page.waitForFunction(()=>document.querySelector('#editor').value==='External update');
// Real screenshot reference, upload, media viewer and screenshot-bound annotation.
await page.locator('#stages button').first().click();
const shot=path.join(workspace,'test-scene.png');await page.screenshot({path:shot});await revealBriefControl(page, '#materialFile'); await page.locator('#materialFile').setInputFiles(shot);await revealBriefControl(page, '#uploadMaterial'); await page.locator('#uploadMaterial').click();await page.waitForSelector('.artifact .media-button');await revealBriefControl(page, '.artifact .media-button'); await page.locator('.artifact .media-button').click();await page.locator('#currentMedia').waitFor();await page.waitForFunction(()=>document.querySelector('#currentMedia').naturalWidth>0);await revealBriefControl(page, '#toggleAnnotation'); await page.locator('#toggleAnnotation').click();const bounds=await page.locator('#selectionLayer').boundingBox();await page.mouse.move(bounds.x+bounds.width*.15,bounds.y+bounds.height*.2);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width*.6,bounds.y+bounds.height*.5);await page.mouse.up();await revealBriefControl(page, '#comment'); await page.locator('#comment').fill('Make this selected section more readable');await revealBriefControl(page, '#saveAnnotation'); await page.locator('#saveAnnotation').click();await page.waitForFunction(()=>document.querySelector('#annotationFeedback').textContent.includes('已保存'));await revealBriefControl(page, '#closeViewer'); await page.locator('#closeViewer').click();assert((await page.locator('#annotations').innerText()).includes('Make this selected'));
// Video seek binds snapshot and default temporal range; manual ranges remain deliberate.
const video=path.join(workspace,'test-video.mp4');const ff=spawnSync('ffmpeg',['-y','-v','error','-f','lavfi','-i','color=c=gray:s=320x180:r=10:d=8','-c:v','libx264','-pix_fmt','yuv420p',video]);assert.equal(ff.status,0);await revealBriefControl(page, '#materialFile'); await page.locator('#materialFile').setInputFiles(video);await revealBriefControl(page, '#uploadMaterial'); await page.locator('#uploadMaterial').click();await page.waitForFunction(()=>document.querySelectorAll('.artifact').length===2);await page.locator('.artifact .artifact-actions button').last().click();await page.waitForFunction(()=>document.querySelector('#currentMedia').readyState>=2);await page.locator('#currentMedia').evaluate(v=>{v.currentTime=5});await page.waitForFunction(()=>document.querySelector('#timeStart').value==='5.0');await revealBriefControl(page, '#comment'); await page.locator('#comment').fill('Whole frame at five seconds');await revealBriefControl(page, '#saveAnnotation'); await page.locator('#saveAnnotation').click();await page.waitForFunction(()=>document.querySelector('#annotationFeedback').textContent.includes('已保存'));let videoState=await (await fetch(`http://127.0.0.1:${port}/api/state`)).json();let last=videoState.project.annotations.at(-1);assert.equal(last.start,5);assert.equal(last.end,5);assert.equal(last.screenshotTime,5);await revealBriefControl(page, '#timeStart'); await page.locator('#timeStart').fill('1');await revealBriefControl(page, '#timeEnd'); await page.locator('#timeEnd').fill('3');await page.locator('#currentMedia').evaluate(v=>{v.currentTime=6});await page.waitForFunction(()=>!document.querySelector('#currentMedia').seeking);assert.equal(await page.locator('#timeStart').inputValue(),'1');await revealBriefControl(page, '#closeViewer'); await page.locator('#closeViewer').click();
const state=await (await fetch(`http://127.0.0.1:${port}/api/state`)).json();assert.equal(state.project.settings.width,1080);assert.equal(state.project.settings.height,1920);assert(state.project.annotations[0].box[2]>.4);assert(fs.existsSync(path.join(workspace,state.project.annotations[0].screenshot)));await page.screenshot({path:'/tmp/studio-interactive-verified.png',fullPage:true});
// API hardening: anonymous writes, traversal and byte-range delivery.
assert.equal((await fetch(`http://127.0.0.1:${port}/api/save`,{method:'POST',body:'{}'})).status,403);const artifact=state.project.stages.requirements.artifacts[0];const range=await fetch(`http://127.0.0.1:${port}/assets/${artifact.path}`,{headers:{Range:'bytes=0-7'}});assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,8);assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: settings, review, dirty guard, CLI polling/conflict, upload, immutable image, box annotation+screenshot, range, CSRF; zero browser errors');
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exit(1)});
