from pathlib import Path
import json, shutil
P=Path(__file__).resolve().parents[1]
texts=[('01_hook','火腿、培根、腊肠，|为什么会被列为一类致癌物？'),('02_evidence','国际癌症研究机构|把食用加工肉归为一类，|意思是：有充分的人体证据，|确认它能导致癌症。|这里证据明确的是结直肠癌。'),('03_distinction','这个分类说的是证据有多充分。|一个人实际增加多少风险，|还要看吃多少、吃多久，|以及原有的风险。'),('04_definition','加工肉，主要指经过|腌制、发酵、烟熏等处理，|来延长保存或增加风味的肉。|新鲜的猪肉、牛肉属于红肉，|在这套分类中是二A类。'),('05_numbers','风险数字也要看清条件。|国际癌症研究机构|二〇一五年的评估|引用了十项研究的分析：|每天多吃五十克加工肉，|结直肠癌的相对风险|估计增加约百分之十八。'),('06_relative','也就是原有风险乘以一点一八。|这个数字描述日常摄入的差别，|不能拿来计算偶尔吃一顿的后果。'),('07_action','日常可以先减少|加工肉出现的次数和分量。|五十克是研究中的比较单位；|当时的评估没有确定|一个安全摄入量。')]
(P/'narration.json').write_text(json.dumps([dict(id=i,text=t) for i,t in texts],ensure_ascii=False,indent=2))
(P/'project.json').write_text(json.dumps(dict(slug='processed-meat',lang='zh',fps=24,width=1920,height=1080,gap=.3,order=[i for i,t in texts],theme='editorial-cream',progress=True,provider='edge',voice='zh-CN-YunxiNeural',rate='+8%'),ensure_ascii=False,indent=2))
(P/'theme.css').write_text(''':root{--bg-0:#F5F0E6;--paper:#FFFCF4;--text:#263E3B;--text-dim:#61736C;--accent:#A54F38;--accent-soft:#EBD6C8;--signal:#367E75;--line:#C9CEC1;--line-soft:#E7E6DB;--food:#C07868;--fat:#EAD5B8;--plate:#E4E6D8;--ink:#263E3B;--accent-glow:rgba(165,79,56,.07)}''')
css='''*{box-sizing:border-box}html,body{margin:0;width:1920px;height:1080px;overflow:hidden;background:var(--bg-0);color:var(--text);font-family:'Noto Sans CJK SC',sans-serif}body:after{content:'';position:absolute;left:80px;right:80px;top:145px;height:1px;background:var(--line)}.kicker{position:absolute;left:96px;top:70px;font-size:25px;font-weight:600;letter-spacing:5px;color:var(--accent)}.brand{position:absolute;right:96px;top:72px;font-size:22px;letter-spacing:4px;color:var(--text-dim)}.num{font-family:Arial,sans-serif}.title{position:absolute;left:96px;top:194px;font-size:82px;line-height:1.25;letter-spacing:-3px;font-weight:700;margin:0}.serif{font-family:'Noto Serif CJK SC',serif;font-weight:600}.muted{color:var(--text-dim)}.accent{color:var(--accent)}.teal{color:var(--signal)}.source{position:absolute;left:96px;bottom:183px;font-size:22px;color:var(--text-dim);letter-spacing:1px}.label{font-size:32px;letter-spacing:2px}.rule{height:2px;background:var(--line)}svg{overflow:visible}svg text{font-family:'Noto Sans CJK SC',sans-serif;fill:var(--text)}.bubble{background:var(--paper);border:2px solid var(--line);border-radius:100px;padding:16px 34px;font-size:30px}.pill{display:inline-block;border:1.5px solid var(--accent);border-radius:40px;padding:10px 24px;font-size:25px;color:var(--accent)}.foot{font-size:27px;color:var(--text-dim)}'''
defs='''<svg style="position:absolute;width:0;height:0"><defs><g id="ham"><path d="M-145 -95 Q-50 -170 100 -90 Q180 -25 112 95 Q30 170 -100 105 Q-195 40 -145 -95" fill="var(--food)" stroke="var(--accent)" stroke-width="8"/><path d="M-117 -77 Q-40 -131 80 -70 Q145 -20 90 73 Q22 129 -78 81 Q-153 30 -117 -77" fill="none" stroke="var(--fat)" stroke-width="12"/><ellipse cx="18" cy="12" rx="34" ry="25" fill="var(--fat)"/><circle cx="-65" cy="-36" r="6" fill="var(--fat)"/><circle cx="57" cy="66" r="8" fill="var(--fat)"/></g><g id="bacon"><path d="M-125 -90 Q-64 -135 -7 -94 T122 -92 L128 90 Q57 54 7 94 T-121 93Z" fill="var(--food)" stroke="var(--accent)" stroke-width="7"/><path d="M-125 -49 Q-62 -88 -5 -47 T125 -50 M-123 22 Q-61 -16 -4 24 T126 23" fill="none" stroke="var(--fat)" stroke-width="22"/></g><g id="sausage"><path d="M-142 -43 Q-40 -135 132 -34" fill="none" stroke="var(--accent)" stroke-width="91" stroke-linecap="round"/><path d="M-142 -43 Q-40 -135 132 -34" fill="none" stroke="var(--food)" stroke-width="74" stroke-linecap="round"/><path d="M-152 -65 l-30 -20 -8 33 34 6 M142 -51 l30 -15 7 36 -33 -4" fill="var(--food)" stroke="var(--accent)" stroke-width="5"/><path d="M-75 -88 l-14 24 M-8 -97 l-8 25 M62 -77 l-10 24" stroke="var(--fat)" stroke-width="9" stroke-linecap="round"/></g></defs></svg>'''
def plate(kind,x,y,scale=1,cl='food'):
 return f'<g class="{cl}" transform="translate({x} {y}) scale({scale})"><circle r="190" fill="var(--plate)"/><circle r="169" fill="none" stroke="var(--paper)" stroke-width="5"/><use href="#{kind}"/></g>'
def write(id,title,body,anim,source='WHO 问答 · 2026-09-23 / IARC 评估 · 2015'):
 html=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>{title}</title><link rel="stylesheet" href="../theme.css"><style>{css}</style><body><div class="kicker">食物与证据 / {id[:2]}</div><div class="brand">一口科学 · FOOD & EVIDENCE</div>{defs}{body}<div class="source">{source}</div><script src="../assets/gsap.min.js"></script><script src="{id}.beats.js"></script><script>var tl=gsap.timeline({{paused:true}});window.__tl=tl;{anim}tl.to({{}},{{duration:0.01}},window.__SEG__.duration);if(!window.__MG_RENDER__){{tl.play(0);}}</script></body></html>'''
 (P/'frames'/f'{id}.html').write_text(html)
write('01_hook','一类致癌物，是什么意思？','''<h1 class="title serif" style="font-size:94px">一类致癌物，<br><span class="accent">是什么意思？</span></h1><div class="opening-note label muted" style="position:absolute;left:102px;top:487px">从火腿、培根、腊肠说起</div><svg width="1920" height="1080">'''+plate('ham',1120,390,.9,'food ham')+plate('bacon',1550,570,.83,'food bacon')+plate('sausage',1100,743,.7,'food sausage')+'''<text x="1350" y="285" font-size="25" fill="var(--text-dim)">PROCESSED MEAT</text></svg>''',"tl.from('.title',{opacity:0,y:25,duration:.9},.1).from('.opening-note',{opacity:0,y:15,duration:.7},.8).from('.ham',{opacity:0,scale:.7,transformOrigin:'center',duration:.9},.1).from('.bacon',{opacity:0,y:'+=40',duration:.8},.5).from('.sausage',{opacity:0,y:'+=35',duration:.8},.9);")
write('02_evidence','分类的依据：充分的人体证据','''<h1 class="title" style="font-size:75px">分类的依据：<span class="accent">人体证据充分</span></h1><div class="group" style="position:absolute;left:103px;top:355px"><div class="label muted">食用加工肉</div><div class="num" style="font-size:225px;line-height:1.1;letter-spacing:-12px">Group <span class="accent">1</span></div><div class="label">IARC 国际癌症研究机构</div></div><svg width="1920" height="1080"><g class="colon" transform="translate(1410 551)"><circle r="230" fill="var(--plate)"/><path d="M-106 115 L-106 -110 Q-106 -145 -70 -145 L105 -145 Q141 -145 141 -107 L141 58 Q141 96 100 96 L28 96 L28 166" fill="none" stroke="var(--signal)" stroke-width="52" stroke-linejoin="round" stroke-linecap="round"/><path d="M-93 106 L-93 -106 Q-93 -130 -68 -130 L102 -130 Q125 -130 125 -103 L125 55 Q125 80 100 80 L28 80" fill="none" stroke="var(--paper)" stroke-width="6" stroke-dasharray="2 23" stroke-linecap="round"/></g></svg><div class="organ label" style="position:absolute;left:1200px;top:810px;width:430px;text-align:center">明确的癌症结局：结直肠癌</div>''',"tl.from('.title',{opacity:0,y:20,duration:.7},.1).from('.group',{opacity:0,x:-30,duration:.8},B('把食用加工肉')).from('.colon',{opacity:0,scale:.85,transformOrigin:'center',duration:.8},B('确认它能导致癌症')).from('.organ',{opacity:0,y:15,duration:.6},B('这里证据明确'));")
write('03_distinction','证据强度与风险大小','''<h1 class="title serif">先分清<span class="accent">两个问题</span></h1><div style="position:absolute;left:101px;top:386px;width:725px"><div class="label muted">分类回答</div><div class="statement" style="font-size:69px;margin-top:28px;line-height:1.45">证据有多充分？</div><svg width="700" height="180"><path class="evidence-line" d="M20 98 H630" stroke="var(--signal)" stroke-width="5"/><g fill="var(--signal)"><circle cx="50" cy="98" r="17"/><circle cx="180" cy="98" r="17"/><circle cx="310" cy="98" r="17"/><circle cx="440" cy="98" r="17"/><circle cx="570" cy="98" r="17"/></g><text x="20" y="163" font-size="28">研究证据 → 因果判断</text></svg></div><div style="position:absolute;left:938px;top:364px;width:2px;height:390px;background:var(--line)"></div><div style="position:absolute;left:1040px;top:386px"><div class="label muted">个人风险还要看</div><div class="risk label" style="margin-top:47px;display:flex;gap:18px"><span class="bubble">吃多少</span><span class="bubble">吃多久</span></div><div class="risk bubble" style="margin-top:24px;text-align:center">原有的风险</div></div><div class="conclusion" style="position:absolute;left:102px;top:790px;font-size:35px;color:var(--accent)">分类本身，不是个人患癌概率</div>''',"tl.from('.title',{opacity:0,y:20,duration:.7},.1).from('.statement',{opacity:0,y:15,duration:.8},.5).from('.evidence-line',{scaleX:0,transformOrigin:'left',duration:1},.8).from('.risk',{opacity:0,y:18,stagger:.3,duration:.6},B('还要看吃多少')).from('.conclusion',{opacity:0,duration:.6},B('以及原有'));")
write('04_definition','什么是加工肉','''<h1 class="title">“加工”描述的是<span class="accent">处理方式</span></h1><svg width="1920" height="1080"><g class="process" transform="translate(365 510)"><circle r="135" fill="var(--plate)"/><path d="M-60 75 V-15 Q0 -65 60 -15 V75Z" fill="var(--paper)" stroke="var(--signal)" stroke-width="5"/><path d="M-35 -48 l-9 -22 M0 -55 v-24 M35 -48 l9 -22" stroke="var(--signal)" stroke-width="7" stroke-linecap="round"/><text text-anchor="middle" y="198" font-size="37">腌制</text></g><g class="process" transform="translate(960 510)"><circle r="135" fill="var(--plate)"/><rect x="-62" y="-73" width="124" height="150" rx="22" fill="var(--paper)" stroke="var(--signal)" stroke-width="5"/><path d="M-58 -78 H58" stroke="var(--signal)" stroke-width="14" stroke-linecap="round"/><circle cx="-25" cy="10" r="13" fill="var(--food)"/><circle cx="25" cy="40" r="17" fill="var(--food)"/><circle cx="27" cy="-33" r="9" fill="var(--food)"/><text text-anchor="middle" y="198" font-size="37">发酵</text></g><g class="process" transform="translate(1555 510)"><circle r="135" fill="var(--plate)"/><path d="M-68 65 Q0 13 68 65" stroke="var(--accent)" stroke-width="30" fill="none" stroke-linecap="round"/><path d="M-42 2 Q-74 -25 -42 -49 T-42 -94 M15 2 Q-16 -25 15 -49 T15 -94 M67 2 Q35 -25 67 -49 T67 -94" stroke="var(--signal)" stroke-width="6" fill="none" stroke-linecap="round"/><text text-anchor="middle" y="198" font-size="37">烟熏</text></g></svg><div class="purpose label muted" style="position:absolute;top:762px;left:100px">延长保存 / 增加风味</div><div class="redmeat" style="position:absolute;top:757px;left:880px;font-size:28px;line-height:1.6">新鲜猪肉、牛肉：红肉 · Group 2A<br><span class="muted">红肉按来源定义，与加工肉可以重叠</span></div>''',"tl.from('.title',{opacity:0,y:20,duration:.7},.1).from('.process',{opacity:0,y:'+=20',stagger:.3,duration:.7},B('腌制')).from('.purpose',{opacity:0,duration:.5},B('来延长保存')).from('.redmeat',{opacity:0,y:10,duration:.7},B('新鲜的猪肉'));")
write('05_numbers','风险数字，先看条件','''<h1 class="title serif">风险数字，<span class="accent">先看条件</span></h1><div class="conditions" style="position:absolute;left:101px;top:358px"><span class="pill">IARC 2015 评估引用</span> <span class="pill">10 项研究分析</span></div><div class="data" style="position:absolute;left:100px;top:455px;width:730px"><div class="label muted">每天多吃加工肉</div><div class="num" style="font-size:190px;letter-spacing:-8px;line-height:1.25">+50<span style="font-size:90px;letter-spacing:0"> g</span></div><div class="label muted">日常摄入量的比较</div></div><svg width="1920" height="1080"><path class="arrow" d="M800 600 H1010 L983 574 M1010 600 L983 626" fill="none" stroke="var(--line)" stroke-width="6"/></svg><div class="result" style="position:absolute;left:1110px;top:455px"><div class="label">结直肠癌<span class="accent">相对风险</span></div><div class="num accent" style="font-size:190px;letter-spacing:-8px;line-height:1.25"><span style="font-size:105px">≈</span>+18<span style="font-size:90px">%</span></div><div class="label muted">估计相对增加</div></div>''',"tl.from('.title',{opacity:0,y:20,duration:.7},.1).from('.conditions',{opacity:0,duration:.6},B('二〇一五年')).from('.data',{opacity:0,y:20,duration:.8},B('每天多吃')).from('.arrow',{opacity:0,duration:.5},B('结直肠癌')).from('.result',{opacity:0,y:20,duration:.8},B('估计增加'));")
write('06_relative','相对风险怎么读','''<h1 class="title serif">相对风险，<span class="accent">这样读</span></h1><div class="formula" style="position:absolute;left:105px;top:360px;font-size:74px">原有风险 <span class="muted">×</span> <span class="num accent" style="font-size:116px">1.18</span></div><div class="chart" style="position:absolute;left:107px;top:552px;width:1030px"><div class="label muted" style="font-size:25px;margin-bottom:28px">相对风险指数 · 基准 = 100</div><div style="display:flex;align-items:center;gap:20px;margin-bottom:22px"><div style="width:690px;height:42px;background:var(--signal)"></div><span class="num" style="font-size:34px">100</span></div><div style="display:flex;align-items:center;gap:20px"><div class="bar118" style="width:814px;height:42px;background:var(--accent)"></div><span class="num" style="font-size:34px">118</span></div></div><div class="limit" style="position:absolute;left:1260px;top:403px;width:530px;border-left:3px solid var(--line);padding-left:48px;font-size:35px;line-height:1.8">每天 +50 g 加工肉<br>结直肠癌相对风险<br><span class="accent">≈ +18%</span><div class="foot" style="margin-top:25px">IARC 2015 评估引用</div></div><div class="caution" style="position:absolute;left:107px;top:785px;font-size:31px;color:var(--accent)">不能用来计算偶尔吃一顿的后果</div>''',"tl.from('.title',{opacity:0,y:20,duration:.7},.1).from('.formula',{opacity:0,y:15,duration:.7},.3).from('.chart',{opacity:0,duration:.6},.8).from('.bar118',{scaleX:.847,transformOrigin:'left',duration:1},1).from('.caution',{opacity:0,y:10,duration:.7},B('不能拿来计算'));")
# closing calendar and plate, both original vector art
calendar=''.join(f'<rect class="meal m{j}" x="{180+(j%7)*88}" y="{470+(j//7)*95}" width="65" height="65" rx="32" fill="var(--accent)"/>' for j in [0,2,4,6,8,10,12])
write('07_action','减少频率，也减少分量','''<h1 class="title serif">减少频率，<span class="accent">也减少分量</span></h1><svg width="1920" height="1080"><g class="calendar"><rect x="110" y="375" width="735" height="338" rx="24" fill="var(--paper)" stroke="var(--line)" stroke-width="3"/><text x="155" y="430" font-size="26">一周餐桌 · 示意</text>'''+calendar+'''</g>'''+plate('ham',1420,540,.85,'portion')+'''<path class="portion-line" d="M1340 455 L1480 617" stroke="var(--paper)" stroke-width="5" stroke-dasharray="12 9"/></svg><div class="closing-note" style="position:absolute;left:112px;top:770px;font-size:31px;line-height:1.6">50 g 是研究比较单位<br><span class="accent">原评估没有确定安全摄入量</span></div><div class="closing-note foot" style="position:absolute;left:1105px;top:780px;line-height:1.7">少一些日常频率<br>少一些每次分量</div>''',"tl.from('.title',{opacity:0,y:20,duration:.7},.1).from('.calendar',{opacity:0,y:15,duration:.7},.5).from('.portion',{opacity:0,duration:.7},.5).to('.m2,.m6,.m10,.m12',{opacity:.12,scale:.7,transformOrigin:'center',stagger:.15,duration:.7},B('加工肉出现')).to('.portion use',{scale:.72,transformOrigin:'center',duration:1.3},B('加工肉出现')+.8).from('.closing-note',{opacity:0,y:10,duration:.7},B('五十克是'));")
print('Authored seven scenes',P)
write('02a_meaning','一类：证据的结论','''<div style="position:absolute;left:100px;top:230px;width:650px"><div class="label muted">读懂分类的第一步</div><h1 class="serif" style="font-size:90px;line-height:1.4;margin-top:40px">看的是<br><span class="accent">证据的确定性</span></h1></div><svg width="1920" height="1080"><g class="papers" transform="translate(1280 475)"><rect x="-190" y="-170" width="370" height="420" rx="12" fill="var(--plate)" transform="rotate(-9)"/><rect x="-180" y="-175" width="370" height="420" rx="12" fill="var(--paper)" stroke="var(--line)" stroke-width="3"/><path d="M-125 -92 H117 M-125 -40 H117 M-125 12 H40 M-125 135 H117 M-125 186 H80" stroke="var(--line)" stroke-width="11" stroke-linecap="round"/><circle class="seal" cx="135" cy="54" r="92" fill="var(--signal)"/><path class="seal" d="M93 57 L122 86 L177 22" stroke="var(--paper)" stroke-width="12" fill="none" stroke-linecap="round"/></g></svg>''',"tl.from('.papers',{opacity:0,y:'+=25',duration:.8},.1).from('.seal',{opacity:0,scale:.5,transformOrigin:'center',duration:.6},1);")
write('03a_exposure','风险与日常摄入有关','''<h1 class="title serif">风险，要放回<span class="accent">日常生活</span></h1><svg width="1920" height="1080"><path d="M230 583 H1660" fill="none" stroke="var(--line)" stroke-width="5"/><g class="dot"><circle cx="280" cy="583" r="84" fill="var(--plate)"/><text x="280" y="603" text-anchor="middle" font-size="52">量</text><text x="280" y="741" text-anchor="middle" font-size="32">日常摄入多少</text></g><g class="dot"><circle cx="945" cy="583" r="84" fill="var(--plate)"/><text x="945" y="603" text-anchor="middle" font-size="52">时间</text><text x="945" y="741" text-anchor="middle" font-size="32">持续多长时间</text></g><g class="dot"><circle cx="1610" cy="583" r="84" fill="var(--accent-soft)"/><text x="1610" y="603" text-anchor="middle" font-size="45">基础</text><text x="1610" y="741" text-anchor="middle" font-size="32">个人原有风险</text></g></svg>''',"tl.from('.title',{opacity:0,y:20,duration:.7},.1).from('.dot',{opacity:0,y:25,stagger:.35,duration:.7},.2);")
write('04a_overlap','两种定义，可以重叠','''<h1 class="title serif">两种定义，<span class="accent">可以重叠</span></h1><svg width="1920" height="1080"><g class="left"><circle cx="770" cy="573" r="225" fill="var(--accent-soft)" fill-opacity=".8"/><text x="683" y="547" font-size="47" text-anchor="middle">红肉</text><text x="655" y="603" font-size="28" text-anchor="middle">按动物来源</text></g><g class="right"><circle cx="1150" cy="573" r="225" fill="var(--plate)" fill-opacity=".8"/><text x="1240" y="547" font-size="47" text-anchor="middle">加工肉</text><text x="1260" y="603" font-size="28" text-anchor="middle">按处理方式</text></g><path d="M960 633 V750" stroke="var(--signal)" stroke-width="3"/><text x="960" y="798" font-size="27" text-anchor="middle">例如：部分猪肉制成的火腿、腊肠</text></svg>''',"tl.from('.title',{opacity:0,y:20,duration:.7},.1).from('.left',{opacity:0,x:-45,duration:.8},.3).from('.right',{opacity:0,x:45,duration:.8},.6);")
write('05a_daily','每天，是关键条件','''<h1 class="title serif">这里的关键词是<span class="accent">“每天”</span></h1><svg width="1920" height="1080"><rect x="102" y="385" width="760" height="360" rx="23" fill="var(--paper)" stroke="var(--line)" stroke-width="3"/><path d="M102 470 H862" stroke="var(--line)" stroke-width="3"/><text x="150" y="441" font-size="27">日常摄入比较</text>'''+''.join(f'<g class="day"><circle cx="{180+j*99}" cy="573" r="30" fill="var(--plate)"/><text x="{180+j*99}" y="648" font-size="23" text-anchor="middle">{["一","二","三","四","五","六","日"][j]}</text></g>' for j in range(7))+'''</svg><div class="daily" style="position:absolute;left:1050px;top:420px"><div class="label">每天多吃加工肉</div><div class="num accent" style="font-size:175px;letter-spacing:-7px">+50<span style="font-size:80px"> g</span></div><div class="foot">50 g 是研究比较单位</div></div>''',"tl.from('.title',{opacity:0,y:20,duration:.7},.1).from('.day',{opacity:0,scale:.7,transformOrigin:'center',stagger:.14,duration:.5},.3).from('.daily',{opacity:0,y:20,duration:.8},.6);",'IARC 2015 评估引用 · 10 项研究分析')
write('06a_not_probability','不要读成患癌概率','''<h1 class="title serif">不要把<span class="accent">相对增加</span>读成概率</h1><div style="position:absolute;left:104px;top:400px"><div class="label muted">研究中的相对风险变化</div><div class="num accent" style="font-size:165px;line-height:1.5">≈ +18%</div><div class="foot">每天 +50 g 加工肉 · 结直肠癌相对风险</div><div class="foot" style="margin-top:10px">IARC 2015 评估引用 · 10 项研究分析</div></div><div class="neq num muted" style="position:absolute;left:944px;top:475px;font-size:125px">≠</div><div class="reading" style="position:absolute;left:1165px;top:471px;font-size:51px;line-height:1.6">个人患癌概率<br><span class="muted" style="font-size:34px">也不是增加 18 个百分点</span></div>''',"tl.from('.title',{opacity:0,y:20,duration:.7},.1).from('.neq',{opacity:0,scale:.7,duration:.7},.4).from('.reading',{opacity:0,y:20,duration:.8},.7);",'IARC 2015 问答 · 相对风险的数学解释')
# Exact ordering, deliberate reading holds; all audio disabled.
order=['01_hook','02_evidence','02a_meaning','03_distinction','03a_exposure','04_definition','04a_overlap','05a_daily','05_numbers','06_relative','06a_not_probability','07_action']
duration=[6,11,4.5,8,4.5,11,5.5,5.5,12,8,6.5,10]
extra={'02a_meaning':'一类，表达的是证据的确定性。','03a_exposure':'摄入量、持续时间和个人基础，|都影响实际风险。','04a_overlap':'红肉按来源定义，|加工肉按处理方式定义。|两者可以重叠。','05a_daily':'这里比较的是每天的摄入量，|五十克是研究比较单位。','06a_not_probability':'相对增加十八个百分点？不对。|相对增加约百分之十八，|不等于个人患癌概率。'}
# Avoid potentially confusing rhetorical misstatement in captions.
extra['06a_not_probability']='相对增加约百分之十八，|不是增加十八个百分点，|也不是个人患癌概率。'
lookup=dict(texts)|extra
(P/'narration.json').write_text(json.dumps([dict(id=i,text=lookup[i],duration=d) for i,d in zip(order,duration)],ensure_ascii=False,indent=2))
pj=json.loads((P/'project.json').read_text());pj.update(order=order,provider='none',audio=False,gap=0,mode='silent');pj.pop('voice',None);pj.pop('rate',None);(P/'project.json').write_text(json.dumps(pj,ensure_ascii=False,indent=2))
print('Silent 12-scene plan:',sum(duration),'seconds')
import re
for sid in order:
 f=P/'frames'/f'{sid}.html';s=f.read_text()
 def exact(m):
  prefix=m.group(1); matches=[b for b in lookup[sid].split('|') if b.startswith(prefix)]
  if len(matches)!=1: raise ValueError((sid,prefix,matches))
  return "B("+json.dumps(matches[0],ensure_ascii=False)+")"
 f.write_text(re.sub(r"B\('([^']+)'\)",exact,s))
with (P/'theme.css').open('a') as f:f.write(':root{--mg-sub-fg:#263E3B;--mg-sub-stroke:#F5F0E6;--mg-track:#E7E6DB}')
# Static proof URL: ?at=seconds&scale=.5; export renderer leaves these absent.
for sid in order:
 f=P/'frames'/f'{sid}.html';s=f.read_text();s=s.replace("if(!window.__MG_RENDER__){tl.play(0);}","const q=new URLSearchParams(location.search);if(q.has('at')){tl.pause(Number(q.get('at')),false);if(q.has('scale')){document.body.style.transform='scale('+Number(q.get('scale'))+')';document.body.style.transformOrigin='top left';}}else if(!window.__MG_RENDER__){tl.play(0);}")
 f.write_text(s)
