/* SPDX-License-Identifier: MIT. Run with existing Playwright; writes QA only to /tmp. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url');const {chromium}=require('../../vendor/html-explainer/node/node_modules/playwright-core');
(async()=>{const out=process.env.SIGNAL_QA_DIR||'/tmp/signal-journey-qa';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:process.env.BROWSER_PATH||'/tmp/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const result={variants:[],limitations:['Native Windows not tested','No final audio/video export in pack tests','Portrait recomposition not provided']};try{for(const variant of ['depth-flight','route-map']){const p=await browser.newPage({viewport:{width:1280,height:720}}),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>errors.push(r.url()));p.on('request',r=>{if(!r.url().startsWith('file:'))external.push(r.url());});const url=pathToFileURL(path.join(__dirname,'../signal-journey/preview.html')).href+'?variant='+variant;
await p.goto(url+'&t=6.3&controls=0');await p.evaluate(()=>document.fonts.ready);const states={};for(const t of [0,1.4,3.5,4.6,6.3,9,10.8,12,1.4,6.3]){await p.evaluate(async t=>{render(t);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));},t);const state=await p.locator('.stage').evaluate(e=>e.outerHTML);if(states[t])assert.equal(state,states[t],'out-of-order seek');states[t]=state;if([1.4,3.5,6.3,10.8].includes(t))await p.screenshot({path:path.join(out,variant+'-'+t+'.png')});}
assert.notEqual(states[1.4],states[6.3]);await p.waitForTimeout(150);assert.equal(await p.locator('.stage').evaluate(e=>e.outerHTML),states[6.3],'freeze drift');await p.evaluate(()=>render(-1));assert.equal(await p.locator('.stage').getAttribute('data-time'),'0.0000');await p.evaluate(()=>render(99));assert.equal(await p.locator('.stage').getAttribute('data-time'),'12.0000');await p.addScriptTag({path:path.join(__dirname,'../shared/engine-bridge.js')});assert.deepEqual(await p.evaluate(()=>{__tl.pause(6.3,false);return [__tl.time(),__tl.duration()]}),[6.3,12]);assert.equal(await p.locator('.stage').evaluate(e=>e.outerHTML),states[6.3],'engine bridge differs');
await p.setViewportSize({width:390,height:844});await p.goto(url+'&t=3.5');const box=await p.locator('.stage').boundingBox();assert(box.x>=-.1&&box.x+box.width<=390.1,'stage cropped');const controls=await p.locator('.player').boundingBox();assert(controls.x>=0&&controls.x+controls.width<=390,'controls cropped');await p.locator('[data-scrub]').fill('2.25');await p.locator('[data-scrub]').dispatchEvent('input');assert.equal(await p.locator('.stage').getAttribute('data-time'),'2.2500');await p.locator('[data-play]').click();await p.waitForFunction(()=>Number(document.querySelector('.stage').dataset.time)>2.3);await p.locator('[data-play]').click();await p.screenshot({path:path.join(out,variant+'-390px.png')});
await p.emulateMedia({reducedMotion:'reduce'});await p.goto(url);const reduced=await p.locator('.stage').getAttribute('data-time');await p.waitForTimeout(100);assert.equal(await p.locator('.stage').getAttribute('data-time'),reduced);assert.equal(await p.locator('[data-play]').getAttribute('aria-pressed'),'false');assert.deepEqual(errors,[]);assert.deepEqual(external,[]);result.variants.push({variant,pass:true,checks:['out-of-order deterministic state','frozen frame','boundary clamp','engine bridge','offline','390px controls','reduced motion']});await p.close();}fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
