const $=id=>document.getElementById(id), stages=['requirements','research','narration','preview','production','export'];
const descriptions={requirements:'把问题、受众和期待说清楚。参考素材、表达边界、系列风格都可以直接写在这里。',research:'从可信的一手来源开始，区分事实、判断与待核实问题。',narration:'先让听的人明白，再让画面跟上。检查语气、解释顺序与事实边界。',preview:'查看真实 HTML 场景截图，按信息与视觉角色挑选代表画面。框选任何需要改动的地方。',production:'把确认的内容变成字幕、节奏与动画。当前先制作无声字幕视频；暂停在具体画面留下反馈。',export:'检查分辨率、字幕、时间轴和最终文件，再交付。'};
const placeholders={requirements:'这次想解释什么？\n观众是谁，他们已经知道什么？\n预计时长、画幅、发布平台？\n希望观众看完明白什么？\n参考资料或喜欢的表达方向？\n\n可以先说一个想法，和 Codex 逐步讨论。',research:'研究摘要、来源链接、关键结论及限制……',narration:'在这里写或修改旁白稿……',preview:'视觉方向、场景安排、代表画面选择理由……',production:'动画、字幕与时间轴检查记录……',export:'最终交付清单与验收记录……'};
const statuses={draft:'草稿',review:'等待确认',approved:'已确认',stale:'需要更新'};
let state,token,active,dirty=false,asset,box=null,drag=null,rangeEdited=false;
const projectKey=new URLSearchParams(location.search).get('project')||'default';
const suffix='?project='+encodeURIComponent(projectKey);
function notice(message,error=false){$('notice').hidden=false;$('notice').textContent=message;$('notice').className=error?'error':'';}
async function api(action,data={}){const res=await fetch('/api/'+action+suffix,{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':token},body:JSON.stringify({...data,revision:state.revision})});const result=await res.json();if(!res.ok)throw Error(result.error||'操作失败');if(result.project)state=result.project;return result;}
async function operation(fn){try{await fn()}catch(e){notice(e.message,true)}}
function assetURL(path){return '/assets/'+path.split('/').map(encodeURIComponent).join('/')+suffix}
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function render(){const s=state.stages[active];$('title').textContent=state.title;$('counter').textContent='创作工作空间 · REV '+String(state.revision).padStart(3,'0');$('modeLabel').textContent=state.selfReview?'样片自审模式已开启':'逐阶段由你确认';$('step').textContent='STAGE '+String(stages.indexOf(active)+1).padStart(2,'0')+' / 06';$('stageTitle').textContent=s.label;$('description').textContent=descriptions[active];$('stageStatus').textContent=statuses[s.status];$('stageStatus').className='badge '+s.status;$('version').textContent='内容版本 v'+s.version;$('editor').value=s.text;$('editor').placeholder=placeholders[active];$('titleRow').hidden=active!=='requirements';$('projectTitle').value=state.title;$('configPanel').hidden=active!=='requirements';$('materialUpload').hidden=!['requirements','research'].includes(active);const settings=state.settings||{aspect:'16:9',width:1920,height:1080,fps:30,duration:90,styleDirection:'',qualityNote:''};for(const key of Object.keys(settings)){if($(key))$(key).value=settings[key]}$('saved').textContent='已保存 · '+new Date(state.updated).toLocaleTimeString();$('submit').disabled=s.status==='review'||s.status==='approved'||s.status==='stale';$('approve').disabled=s.status!=='review';$('reviewHelp').textContent=s.status==='stale'?'前面内容已改变。让 Codex 更新本阶段，再提交审核。':'先检查内容，再提交审核。确认后进入下一阶段。';$('stages').replaceChildren();stages.forEach((key,i)=>{const st=state.stages[key],b=element('button',undefined,key===active?'selected':'');b.append(element('span',String(i+1).padStart(2,'0'),'num'),element('span',st.label),element('span',st.status==='approved'?'✓':st.status==='stale'?'↻':'·','dot'));b.onclick=()=>{if(dirty&&!confirm('有未保存的修改，确定切换吗？'))return;active=key;dirty=false;render()};$('stages').append(b)});renderArtifacts(s);renderAnnotations();dirty=false;}
function renderArtifacts(s){$('artifacts').replaceChildren();s.artifacts.forEach(a=>{const card=element('article',undefined,'artifact'),ext=a.path.split('.').pop().toLowerCase();if(['png','jpg','jpeg','webp'].includes(ext)){const im=element('img');im.src=assetURL(a.path);im.alt=a.label;card.append(im)}else if(['mp4','webm'].includes(ext)){const v=element('video');v.src=assetURL(a.path);v.preload='metadata';v.muted=true;card.append(v)}else card.append(element('div',ext.toUpperCase(),'file'));const info=element('div',undefined,'info');info.append(element('h3',a.label||a.path),element('p',`${a.role||'项目产物'} · v${a.version}${a.version!==s.version?' · 历史版本':''}`));if(['png','jpg','jpeg','webp','mp4','webm'].includes(ext)){const btn=element('button','查看与批注');btn.onclick=()=>openAsset(a,ext);info.append(btn)}const link=element('a','下载文件');link.href=assetURL(a.path);link.download=a.path.split('/').pop();info.append(link);card.append(info);$('artifacts').append(card)})}
function renderAnnotations(){$('annotations').replaceChildren();const anns=state.annotations.filter(a=>a.stage===active);if(!anns.length)$('annotations').append(element('div','打开场景截图或视频，框选区域并留下修改意见。','empty'));anns.slice().reverse().forEach(a=>{const row=element('div',undefined,'annotation'),body=element('div');body.append(element('small',`v${a.version} · ${a.start.toFixed(1)}–${a.end.toFixed(1)} 秒 · 截图 ${(a.screenshotTime??a.start).toFixed(1)} 秒 · ${a.box?'局部框选':'整体意见'}${a.resolved?' · 已处理':''}`),element('p',a.comment));if(a.screenshot){const link=element('a','查看批注时的截图');link.href=assetURL(a.screenshot);link.target='_blank';body.append(link)}const b=element('button',a.resolved?'重新打开':'标记已处理');b.onclick=()=>operation(async()=>{await api('resolve',{id:a.id,resolved:!a.resolved});renderAnnotations()});row.append(body,b);$('annotations').append(row)})}
$('editor').oninput=$('projectTitle').oninput=()=>{dirty=true;$('saved').textContent='有未保存修改'};
$('save').onclick=()=>operation(async()=>{await api('save',{stage:active,text:$('editor').value,title:$('projectTitle').value,...(active==='requirements'?{settings:{aspect:$('aspect').value,width:Number($('width').value),height:Number($('height').value),fps:Number($('fps').value),duration:Number($('duration').value),styleDirection:$('styleDirection').value,qualityNote:$('qualityNote').value}}:{})});render();notice('已保存。后续依赖内容如有变化，需要重新审核。')});
$('submit').onclick=()=>operation(async()=>{if(dirty)throw Error('请先保存修改');await api('submit',{stage:active});render();notice('已提交，检查后可确认进入下一阶段。')});
$('approve').onclick=()=>operation(async()=>{if(dirty)throw Error('有未保存的修改，请先保存并重新提交审核');await api('approve',{stage:active,by:'human',note:$('reviewNote').value});active=state.active;render();notice('已确认，进入下一阶段。')});
$('revise').onclick=()=>operation(async()=>{if(dirty)throw Error('请先保存当前修改，再开始新修订');if(!confirm('开始新修订？后续依赖产物将标记为需要更新，历史内容保留。'))return;await api('revise',{stage:active});render();notice('已开始新版本；把修改意见告诉 Codex。')});
$('undo').onclick=()=>operation(async()=>{if(dirty)throw Error('请先保存当前修改，再撤销；或刷新并明确放弃未保存内容');if(!confirm('撤销上次项目更改？产物文件不会被删除。'))return;await api('undo');active=state.active;render();notice('已恢复上一个项目快照。')});
function openAsset(a,ext){asset=a;box=null;rangeEdited=false;$('selection').style.display='none';$('media').replaceChildren();const isVideo=['mp4','webm'].includes(ext),m=element(isVideo?'video':'img');m.src=assetURL(a.path);m.id='currentMedia';if(isVideo){m.controls=true;m.onpause=m.onseeked=()=>{if(!rangeEdited){$('timeStart').value=m.currentTime.toFixed(1);$('timeEnd').value=m.currentTime.toFixed(1)}};}else m.alt=a.label;$('media').append(m);$('assetTitle').textContent=a.label;$('assetMeta').textContent=`${state.stages[active].label} · v${a.version}`;$('timeStart').value=$('timeEnd').value=0;$('comment').value='';$('annotationFeedback').textContent='';$('captureTime').hidden=!isVideo;$('selectionLayer').style.bottom=isVideo?'40px':'0';$('viewer').showModal();}
function position(e){const r=$('selectionLayer').getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]}
$('selectionLayer').onpointerdown=e=>{const m=$('currentMedia');if(m.tagName==='VIDEO'){rangeEdited=false;m.pause();$('timeStart').value=$('timeEnd').value=m.currentTime.toFixed(1)}drag=position(e);$('selectionLayer').setPointerCapture(e.pointerId)};
$('selectionLayer').onpointermove=e=>{if(!drag)return;const p=position(e);box=[Math.min(drag[0],p[0]),Math.min(drag[1],p[1]),Math.abs(drag[0]-p[0]),Math.abs(drag[1]-p[1])];Object.assign($('selection').style,{display:'block',left:box[0]*100+'%',top:box[1]*100+'%',width:box[2]*100+'%',height:box[3]*100+'%'})};
$('selectionLayer').onpointerup=()=>{drag=null;if(box&&(box[2]<.005||box[3]<.005))box=null};
$('clearBox').onclick=()=>{box=null;$('selection').style.display='none'};
$('captureTime').onclick=()=>{rangeEdited=false;const m=$('currentMedia');m.pause();$('timeStart').value=$('timeEnd').value=m.currentTime.toFixed(1)};
$('saveAnnotation').onclick=()=>operation(async()=>{const m=$('currentMedia'),isVideo=m.tagName==='VIDEO';if(isVideo&&!m.paused){m.pause();if(!rangeEdited)$('timeStart').value=$('timeEnd').value=m.currentTime.toFixed(1)}const canvas=document.createElement('canvas');canvas.width=isVideo?m.videoWidth:m.naturalWidth;canvas.height=isVideo?m.videoHeight:m.naturalHeight;if(!canvas.width)throw Error('画面尚未载入');const comment=$('comment').value.trim();if(!comment)throw Error('请先填写修改意见');canvas.getContext('2d').drawImage(m,0,0);const result=await api('capture',{data:canvas.toDataURL('image/png')});let adjusted=box;if(box&&isVideo){const full=m.getBoundingClientRect(),overlay=$('selectionLayer').getBoundingClientRect();adjusted=[box[0],box[1]*overlay.height/full.height,box[2],box[3]*overlay.height/full.height]}await api('annotation',{stage:active,asset:asset.path,screenshot:result.path,screenshotTime:isVideo?m.currentTime:0,version:asset.version,start:Number($('timeStart').value),end:Number($('timeEnd').value),box:adjusted,comment});$('annotationFeedback').textContent='批注与截图已保存';$('comment').value='';renderAnnotations()});
$('closeViewer').onclick=()=>{$('currentMedia')?.pause?.();$('viewer').close()};$('help').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();window.onbeforeunload=e=>{if(dirty){e.preventDefault();e.returnValue=''}};
fetch('/api/state'+suffix).then(r=>r.json()).then(r=>{state=r.project;token=r.token;active=state.active;render()}).catch(e=>notice('无法连接本地工作台：'+e.message,true));

fetch('/api/projects').then(r=>r.json()).then(data=>{data.projects.forEach(p=>{const option=element('option',p.title);option.value=p.id;$('projectPicker').append(option)});$('projectPicker').value=projectKey});
$('projectPicker').onchange=()=>{if(dirty&&!confirm('有未保存修改，确定切换项目吗？')){$('projectPicker').value=projectKey;return}location.href='/?project='+encodeURIComponent($('projectPicker').value)};

let updateNoticeRevision=null;
async function refreshProject(manual=false){
 if(manual&&dirty&&!confirm('刷新会放弃当前未保存的修改。请先复制需要保留的文字。确定刷新吗？'))return;
 const response=await fetch('/api/state'+suffix);if(!response.ok)throw Error('无法读取项目更新');const result=await response.json();token=result.token;
 if(!state||result.project.revision===state.revision)return;
 if(dirty&&!manual){if(updateNoticeRevision!==result.project.revision){notice('Codex 或另一窗口已更新项目。你的未保存文字仍保留；请复制需要保留的内容，再点“刷新项目”核对最新版本。',true);updateNoticeRevision=result.project.revision}return}
 state=result.project;render();if(manual)notice('已载入最新项目状态。');
}
$('refresh').onclick=()=>operation(()=>refreshProject(true));
setInterval(()=>{if(state&&!document.hidden&&!$('viewer').open)refreshProject().catch(()=>{$('saved').textContent='连接暂时中断，稍后自动重试'})},3000);

for(const field of ['aspect','width','height','fps','duration','styleDirection','qualityNote'])$(field).oninput=()=>{dirty=true;$('saved').textContent='有未保存修改'};
$('aspect').onchange=()=>{const dimensions={'16:9':[1920,1080],'9:16':[1080,1920],'1:1':[1080,1080]};if(dimensions[$('aspect').value])[$('width').value,$('height').value]=dimensions[$('aspect').value];dirty=true};
$('uploadMaterial').onclick=()=>operation(async()=>{if(dirty)throw Error('请先保存文字和配置，再导入参考文件');const file=$('materialFile').files[0];if(!file)throw Error('请先选择文件');if(file.size>8000000)throw Error('文件超过8 MB，请由 Codex 直接复制到项目目录');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});await api('upload',{name:file.name,data,stage:active});render();notice('参考文件已保存到本地项目，Codex 可继续读取。')});

$('timeStart').oninput=$('timeEnd').oninput=()=>{rangeEdited=true};
