'use strict';
const $ = id => document.getElementById(id);
const stages = ['requirements', 'narration', 'preview', 'production', 'export'];
const labels = {requirements:'需求沟通',narration:'文案',preview:'静态预览',production:'视频制作',export:'导出交付'};
const descriptions = {
  requirements:'先说清想法，放入自己的参考。剩下的调研、文案与制作，交给 Codex。',
  narration:'Codex 先结合你的资料调研，再组织成完整文案。一起检查内容、语气与事实依据。',
  preview:'查看真实场景截图；选择音乐时也在这里试听短样，一起确认创作方向。图片可放大，音乐可播放、暂停和拖动进度。',
  production:'直接播放视频，检查节奏、字幕与画面。需要修改时，放大并暂停在具体时刻。',
  export:'最后检查成片与交付文件。下载后就可以使用了。'
};
const placeholders = {requirements:'这次想讲什么？\n给谁看？他们已经知道哪些？\n希望观众看完记住什么？\n\n可以写几句话，也可以直接放入完整需求。\n有必须保留的事实、表达边界或参考链接，也写在这里。',narration:'Codex 会在这里写入调研后的文案，保留来源与事实边界。你也可以直接修改…',preview:'视觉方向、场景安排与代表画面的选择理由…',production:'动画、字幕、配音与时间轴的检查记录…',export:'最终文件、实际时长与验收记录…'};
const statuses={draft:'草稿',review:'等待确认',approved:'已确认',stale:'需要更新'};
const modeNames={manual:'全流程',semi:'半自动',auto:'全自动'};
let state, token, active='requirements', dirty=false, busy=false, asset, assetStage, box=null, drag=null, rangeEdited=false;
let themes=[], voices=[], voiceRegistry={}, selectedThemeId='original', themeFormDirty=false, modalOrigin=null;
let updateNoticeRevision=null, currentDialog=null, workspacePath='';
const projectKey=new URLSearchParams(location.search).get('project')||'default';
const suffix='?project='+encodeURIComponent(projectKey);
const defaults={aspect:'16:9',width:1920,height:1080,fps:30,duration:90,durationMode:'approx',durationMin:60,durationMax:120,styleDirection:'',qualityNote:'',themeId:'original',voicePresetId:'',audio_mode:'silent',bgm_mode:'none',bgm_direction:'',bgm_upload:'',azure_voice:'zh-CN-XiaoxiaoNeural',azure_rate:'0%',edge_voice:'zh-CN-YunxiNeural',edge_rate:'0%'};
function notice(message,error=false){$('notice').hidden=false;$('notice').textContent=message;$('notice').className=error?'error':'';const feedback=currentDialog==='viewer'?$('annotationFeedback'):currentDialog==='settingsDialog'?$('themeSaveFeedback'):currentDialog==='voiceDialog'?$('voiceFeedback'):currentDialog==='newVideoDialog'?$('newVideoFeedback'):null;if(feedback){feedback.textContent=message;feedback.classList.toggle('feedback-error',error);}}
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function assetURL(path){return '/assets/'+path.split('/').map(encodeURIComponent).join('/')+suffix;}
function markDirty(){dirty=true;$('saved').textContent='有未保存修改';$('save').textContent='保存修改';if(state)renderNextStep();}
function effectiveMode(){return document.querySelector('input[name="workflowMode"]:checked')?.value||state.workflowMode||'manual';}
function provider(){return $('voiceProvider').value;}
function audioMode(){return document.querySelector('input[name="soundMode"]:checked').value==='silent'?'silent':provider();}
async function api(action,data={}){const res=await fetch('/api/'+action+suffix,{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':token},body:JSON.stringify({...data,revision:state.revision})});const result=await res.json();if(!res.ok)throw Error(result.error||'操作失败');if(result.project)state=result.project;return result;}
async function operation(fn,button){if(busy)return;busy=true;const locked=[...document.querySelectorAll('input,textarea,select')].filter(el=>!el.disabled);locked.forEach(el=>el.disabled=true);const wasDisabled=button?.disabled;if(button)button.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{busy=false;locked.forEach(el=>el.disabled=false);if(button)button.disabled=wasDisabled||false;if(state)renderNextStep();}}
function formatTime(){return new Date(state.updated).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}
function render(){
  active=stages.includes(active)?active:'narration';const s=state.stages[active],isBrief=active==='requirements';
  $('title').textContent=state.title;if(projectKey!=='sample'&&$('projectPicker').selectedOptions[0])$('projectPicker').selectedOptions[0].textContent=state.title;$('modeLabel').textContent=(modeNames[state.workflowMode]||'全流程')+' · '+(state.selfReview?'已授权样片自审':state.workflowMode==='auto'?'需求后持续到成片':state.workflowMode==='semi'?'静态预览由你确认':'逐步由你确认');
  $('step').textContent='STEP '+String(stages.indexOf(active)+1).padStart(2,'0')+' / 05';$('stageTitle').textContent=labels[active];$('description').textContent=descriptions[active];$('stageStatus').textContent=statuses[s.status]||s.status;$('stageStatus').className='badge '+s.status;
  $('version').textContent='版本 '+s.version;$('editor').value=s.text;$('editor').placeholder=placeholders[active];$('projectTitle').value=state.title;
  $('titleRow').hidden=!isBrief;$('configPanel').hidden=!isBrief;$('requirementsOptions').hidden=!isBrief;$('materialUpload').hidden=!isBrief;$('workspaceGrid').classList.toggle('single',!isBrief);
  $('editorLabel').textContent=isBrief?'这支视频想讲什么？':active==='narration'?'文案与调研依据':'制作说明';$('editorPrompt').textContent=isBrief?'主题、受众与想让观众记住的事':active==='narration'?'检查讲述顺序、表达与关键来源':'内容说明与检查记录';$('editorHint').textContent=isBrief?'先保存想法，准备好后再开始':'修改前面内容后，下游会需要重新核对';
  const settings={...defaults,...state.settings};for(const key of Object.keys(settings)){if($(key))$(key).value=key.endsWith('_rate')?parseInt(settings[key],10):settings[key];}
  selectedThemeId=settings.themeId||'original';document.querySelector(`input[name="workflowMode"][value="${state.workflowMode||'manual'}"]`).checked=true;
  document.querySelector(`input[name="soundMode"][value="${settings.audio_mode==='silent'?'silent':'voiced'}"]`).checked=true;$('voiceProvider').value=settings.audio_mode==='azure'?'azure':'edge';
  renderDuration();renderAudioControls();renderBgmControls();renderSelectedTheme();$('saved').textContent='已保存 · '+formatTime();$('save').textContent=s.status==='draft'?'保存草稿':'保存修改';dirty=false;
  $('stages').replaceChildren();stages.forEach((key,i)=>{const st=state.stages[key],b=element('button',undefined,key===active?'selected':'');b.type='button';b.setAttribute('aria-current',key===active?'step':'false');b.append(element('span',String(i+1).padStart(2,'0'),'num'),element('span',labels[key]),element('span',st.status==='approved'?'✓':st.status==='stale'?'↻':'·','dot'));b.onclick=()=>{if(!busy)navigateStage(key);};$('stages').append(b);});
  renderArtifacts(s);renderAnnotations();renderReview();renderNextStep();
}
function navigateStage(key,push=true){if(key===active)return true;if(dirty&&!confirm('有未保存的修改。放弃这些修改并切换步骤吗？'))return false;$('bgmSourceAudio').pause();active=key;render();if(push)history.pushState({stage:active},'');return true;}
function renderDuration(){$('approxDuration').hidden=$('durationMode').value==='range';$('rangeDuration').hidden=$('durationMode').value!=='range';}
function renderAudioControls(){const sound=audioMode(),p=provider();$('voiceSettings').hidden=sound==='silent';$('edgeControls').hidden=p!=='edge';$('azureControls').hidden=p!=='azure';$('azureHelp').hidden=p!=='azure';$('providerHelp').textContent=p==='edge'?'免 Azure 密钥。实际配音会将文案发送至 Microsoft Edge 在线语音服务。':'使用你自己的 Azure Speech 资源。实际配音会将文案发送至所配置的区域。';const id=$(p+'_voice').value,voice=voices.find(v=>v.id===id);$('selectedVoiceName').textContent=voice?`${voice.name} · ${voice.gender}`:id;$('audioHelp').textContent=sound==='silent'?'不生成配音。以字幕与画面表达内容，保留足够阅读时间。':'试听只播放本地预录样本。实际配音由 Codex 在文案确定后执行，保存设置不会发起合成请求。';syncVoicePreviewRate();}
function renderBgmControls(){const mode=$('bgm_mode').value;$('bgmDirectionPanel').hidden=mode!=='ai';$('bgmUploadPanel').hidden=mode!=='upload';$('bgmWorkflowHelp').hidden=mode==='none';$('bgmUploadName').textContent=state.settings?.bgm_upload?'已导入：'+state.settings.bgm_upload.split('/').pop().replace(/^bgm-[a-f0-9]{32}-/,''):'尚未导入音乐；请先选择文件，再点击“导入音乐”。';const source=$('bgmSourceAudio'),path=state.settings?.bgm_upload;source.hidden=mode!=='upload'||!path;if(source.hidden){source.pause();}else if(source.getAttribute('src')!==assetURL(path)){source.src=assetURL(path);}$('bgmHelp').textContent=mode==='none'?'背景音乐与配音独立选择；不配音也可以有音乐。':mode==='ai'?'由当前 Codex 创作和制作；不需要额外的音乐 API 密钥。':'使用导入的音频作为音乐来源；AI 会根据视频节奏安排与混音。';}
function renderNextStep(){if(!state)return;const next=state.nextAction||{stage:state.active,actor:'human',action:'submit_requirements'},request=state.taskRequest;const b=$('continue');b.disabled=busy;b.hidden=false;$('bridgeDetails').hidden=next.actor!=='agent';$('pauseRequest').hidden=!['queued','running'].includes(request?.status)||next.actor!=='agent';
  if(next.action==='complete'){$('nextTitle').textContent='这支视频已完成';$('nextDescription').textContent='最终视频与相关文件已准备好，可以前往导出页查看与下载。';b.textContent='查看交付文件';b.disabled=active==='export';}
  else if(active==='requirements'&&(state.stages.requirements.status!=='approved'||dirty)){$('nextTitle').textContent='准备好后，把需求交给 Codex';$('nextDescription').textContent='确认会保存当前需求与设置，并按所选模式开始推进。';b.textContent='确认需求并开始 →';}
  else if(next.action==='resume'){$('nextTitle').textContent='已暂停继续请求';$('nextDescription').textContent='恢复后，Codex 会按当前模式继续。已启动的渲染可能仍在结束当前步骤。';b.textContent='恢复并继续 →';}
  else if(next.actor==='human'){$('nextTitle').textContent=`${labels[next.stage]}等待你确认`;$('nextDescription').textContent='检查内容和实际产物后继续；有修改意见可以先批注或退回。';b.textContent=active===next.stage?'确认并继续 →':'去检查'+labels[next.stage];}
  else {const running=request?.status==='running',queued=request?.status==='queued';$('nextTitle').textContent=running?`Codex 已领取任务 · ${labels[next.stage]}`:queued?'任务已提交，等待 Codex 接手':'下一步交给 Codex';$('nextDescription').textContent=request?.note?`执行提示：${request.note}`:running?`将继续到${next.checkpoint?labels[next.checkpoint]+'的确认点':'最终导出'}，实际进度会在这里更新。`:queued?'请保持当前 Codex 会话进行中。若尚未接手，回到同一项目对话说“继续当前视频项目”。':`将制作${labels[next.stage]}，按所选模式推进。`;b.textContent=running?'正在制作…':queued?'等待 Codex 接手':'交给 Codex 继续 →';b.disabled=busy||running||queued;}
}
function renderReview(){const s=state.stages[active],relevant=active!=='requirements'&&(s.text.trim()||s.artifacts.length||s.status==='review'||s.status==='stale');$('reviewPanel').hidden=!relevant;$('reviewTitle').textContent=s.status==='approved'?'这一阶段已确认':s.status==='stale'?'前面的内容变了，需要更新':'检查后再继续';$('reviewHelp').textContent=s.status==='stale'?'旧内容与文件仍保留。请让 Codex 更新本阶段，再重新确认。':s.status==='approved'?'需要调整时可以开始新修订，历史产物不会被删除。':'检查文字与真实产物后确认；也可先留下具体修改意见。';$('submit').hidden=s.status!=='draft';$('submit').disabled=s.status!=='draft';$('approve').hidden=s.status!=='review';$('approve').disabled=s.status!=='review';$('revise').textContent=s.status==='approved'?'开始新修订':'退回修改';}
function settingsPayload(){const p=provider();return{aspect:$('aspect').value,width:Number($('width').value),height:Number($('height').value),fps:Number($('fps').value),duration:Number($('duration').value),durationMode:$('durationMode').value,durationMin:Number($('durationMin').value),durationMax:Number($('durationMax').value),styleDirection:$('styleDirection').value,qualityNote:$('qualityNote').value,themeId:selectedThemeId,voicePresetId:voices.some(v=>v.id===$(p+'_voice').value)?$(p+'_voice').value:'',audio_mode:audioMode(),bgm_mode:$('bgm_mode').value,bgm_direction:$('bgm_direction').value,bgm_upload:state.settings?.bgm_upload||'',bgm_gain_db:state.settings?.bgm_gain_db??0,bgm_ducking:state.settings?.bgm_ducking??true,bgm_fade_out:state.settings?.bgm_fade_out??1.5,azure_voice:$('azure_voice').value.trim(),azure_rate:$('azure_rate').value+'%',edge_voice:$('edge_voice').value.trim(),edge_rate:$('edge_rate').value+'%'};}
async function saveDraft(){const wantedMode=effectiveMode();await api('save',{stage:active,text:$('editor').value,title:$('projectTitle').value,...(active==='requirements'?{settings:settingsPayload()}:{})});if(active==='requirements'&&wantedMode!==(state.workflowMode||'manual'))await api('mode',{workflowMode:wantedMode});dirty=false;}
$('save').onclick=()=>operation(async()=>{await saveDraft();render();notice('已保存。准备好后再确认继续。');},$('save'));
$('continue').onclick=()=>operation(async()=>{const next=state.nextAction;
  if(next?.action==='complete'){navigateStage('export');return;}
  if(active==='requirements'&&(state.stages.requirements.status!=='approved'||dirty)){await saveDraft();if(state.stages.requirements.status!=='review')await api('submit',{stage:'requirements'});await api('approve',{stage:'requirements',by:'human',note:'用户在工作台确认需求并开始；运行模式：'+modeNames[state.workflowMode]});active=state.active;render();notice('需求已确认，任务已写入本地项目，等待 Codex 接手。');history.replaceState({stage:active},'');return;}
  if(next?.action==='resume'){if(dirty)await saveDraft();await api('request');render();notice('已恢复继续请求，等待 Codex 接手。');return;}
  if(next?.actor==='human'){if(active!==next.stage){navigateStage(next.stage);return;}if(dirty)throw Error('有未保存的修改，请先保存并重新提交审核');await api('approve',{stage:active,by:'human',note:$('reviewNote').value});active=state.active;render();notice('已确认，下一步任务已更新。');history.replaceState({stage:active},'');return;}
  if(dirty)await saveDraft();await api('request',{stage:next?.stage});render();notice('任务已提交。当前 Codex 会话可读取任务并继续。');
},$('continue'));
$('pauseRequest').onclick=()=>operation(async()=>{await api('cancel',{id:state.taskRequest.id});renderNextStep();notice('继续请求已暂停。已启动的渲染不会被强制终止；Codex 会在后续步骤检查暂停状态。');},$('pauseRequest'));
$('submit').onclick=()=>operation(async()=>{if(dirty)throw Error('请先保存修改，再提交审核');await api('submit',{stage:active});render();notice('已提交，请检查后确认。');},$('submit'));
$('approve').onclick=()=>operation(async()=>{if(dirty)throw Error('有未保存的修改，请先保存并重新提交审核');await api('approve',{stage:active,by:'human',note:$('reviewNote').value});active=state.active;render();history.replaceState({stage:active},'');notice('已确认，下一步任务已更新。');},$('approve'));
$('revise').onclick=()=>operation(async()=>{if(dirty)throw Error('请先保存当前修改，再开始新修订');if(!confirm('开始新修订？后续依赖产物将标记为需要更新，历史内容保留。'))return;await api('revise',{stage:active});render();notice('已开始新修订。更新内容或批注后，再交给 Codex 继续。');},$('revise'));
$('undo').onclick=()=>operation(async()=>{if(dirty)throw Error('请先保存修改，或刷新并明确放弃未保存内容');if(!confirm('撤销上次项目更改？已生成的文件不会被删除。'))return;await api('undo');active=state.active;render();history.replaceState({stage:active},'');notice('已恢复上一个项目快照。');},$('undo'));
$('copyInstruction').onclick=()=>operation(async()=>{const text='请继续当前视频项目：工作目录 '+workspacePath+'；先读取 python -m app.cli --workspace '+JSON.stringify(workspacePath)+' status，按已保存的需求、参考资料和 workflowMode 执行，先调研再写文案，在当前模式要求的人工确认点停下。';try{await navigator.clipboard.writeText(text);$('copyInstruction').textContent='已复制';}catch{notice('无法自动复制，请复制这段指令发给 Codex：'+text);}});
function renderArtifacts(s){$('artifacts').querySelectorAll('audio,video').forEach(m=>m.pause());$('artifacts').replaceChildren();$('artifactsSection').hidden=!s.artifacts.length;$('artifactsTitle').textContent=active==='requirements'?'你的参考资料':'阶段产物';s.artifacts.forEach(a=>{const card=element('article',undefined,'artifact'),ext=a.path.split('.').pop().toLowerCase();let inlineVideo;
  if(['png','jpg','jpeg','webp'].includes(ext)){const btn=element('button',undefined,'media-button');btn.setAttribute('aria-label','放大查看 '+(a.label||'图片'));const im=element('img');im.src=assetURL(a.path);im.alt=a.label||'项目图片';im.loading='lazy';btn.append(im);btn.onclick=()=>openAsset(a,ext);card.append(btn);}
  else if(['mp4','webm'].includes(ext)){inlineVideo=element('video');inlineVideo.src=assetURL(a.path);inlineVideo.preload='metadata';inlineVideo.controls=true;inlineVideo.playsInline=true;inlineVideo.setAttribute('aria-label',a.label||'项目视频');card.append(inlineVideo);}
  else if(['wav','mp3','m4a','ogg','flac'].includes(ext)){const audio=element('audio');audio.src=assetURL(a.path);audio.preload='metadata';audio.controls=true;audio.setAttribute('aria-label',a.label||'项目音频');card.append(audio);}
  else card.append(element('div',ext.toUpperCase(),'file'));
  const info=element('div',undefined,'info');info.append(element('h3',a.label||a.path),element('p',`${a.role||'项目产物'} · v${a.version}${a.version!==s.version?' · 历史版本':''}`));const actions=element('div',undefined,'artifact-actions');if(['png','jpg','jpeg','webp','mp4','webm'].includes(ext)){const btn=element('button',inlineVideo?'放大与批注':'查看与批注');btn.onclick=()=>{const at=inlineVideo?.currentTime||0;inlineVideo?.pause();openAsset(a,ext,at);};actions.append(btn);}const link=element('a','下载文件');link.href=assetURL(a.path);link.download=a.label||a.path.split('/').pop();actions.append(link);info.append(actions);card.append(info);$('artifacts').append(card);
});}
function renderAnnotations(){$('annotations').replaceChildren();const anns=state.annotations.filter(a=>a.stage===active);$('commentsSection').hidden=active==='requirements'&&!anns.length;if(!anns.length)$('annotations').append(element('div','打开图片或视频，可以留下整体意见，也可以开启框选做局部批注。','empty'));anns.slice().reverse().forEach(a=>{const row=element('div',undefined,'annotation'),body=element('div');body.append(element('small',`v${a.version} · ${a.start.toFixed(1)}–${a.end.toFixed(1)} 秒 · ${a.box?'局部框选':'整体意见'}${a.resolved?' · 已处理':''}`),element('p',a.comment));if(a.screenshot){const link=element('a','查看批注时的截图');link.href=assetURL(a.screenshot);link.target='_blank';link.rel='noopener';body.append(link);}const b=element('button',a.resolved?'重新打开':'标记已处理');b.onclick=()=>operation(async()=>{await api('resolve',{id:a.id,resolved:!a.resolved});renderAnnotations();},b);row.append(body,b);$('annotations').append(row);});}
function showDialog(id){const dialog=$(id);if(dialog.open)return;modalOrigin=document.activeElement;currentDialog=id;dialog.showModal();history.pushState({stage:active,dialog:id},'');}
function canCloseDialog(id){if(id==='newVideoDialog'&&$('newVideoName').value.trim())return confirm('新视频还没创建。保留名称并关闭窗口吗？');if(id==='settingsDialog'&&themeFormDirty)return confirm('自定义主题还没保存。保留表单并关闭窗口吗？');if(id==='viewer'&&$('comment').value.trim())return confirm('批注还没保存。放弃这条批注并关闭吗？');return true;}
function closeDialog(id,viaHistory=false){if(!$(id).open)return true;if(id==='credentialDialog')clearCredentialInput();if(!canCloseDialog(id))return false;if(document.fullscreenElement&&$(id).contains(document.fullscreenElement))document.exitFullscreen().catch(()=>{});$(id).querySelectorAll('video,audio').forEach(m=>m.pause());$(id).close();currentDialog=null;modalOrigin?.focus();if(!viaHistory&&history.state?.dialog===id)history.back();return true;}
for(const [id,button] of [['newVideoDialog','closeNewVideo'],['viewer','closeViewer'],['themeDialog','closeTheme'],['voiceDialog','closeVoice'],['settingsDialog','closeSettings'],['helpDialog','closeHelp'],['credentialDialog','closeCredentials']]){$(button).onclick=()=>closeDialog(id);$(id).addEventListener('cancel',e=>{e.preventDefault();closeDialog(id);});}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.fullscreenElement){e.preventDefault();e.stopImmediatePropagation();document.exitFullscreen().catch(()=>{});}},true);
window.addEventListener('popstate',e=>{if(currentDialog){if(!closeDialog(currentDialog,true)){history.pushState({stage:active,dialog:currentDialog},'');return;}}const target=e.state?.stage;if(target&&target!==active&&!navigateStage(target,false))history.pushState({stage:active},'');});
function openAsset(a,ext,time=0){asset=a;assetStage=active;box=null;drag=null;rangeEdited=false;$('selection').style.display='none';$('selectionLayer').hidden=true;$('toggleAnnotation').setAttribute('aria-pressed','false');$('media').replaceChildren();const isVideo=['mp4','webm'].includes(ext),m=element(isVideo?'video':'img');m.src=assetURL(a.path);m.id='currentMedia';if(isVideo){m.controls=true;m.playsInline=true;m.preload='metadata';m.onloadedmetadata=()=>{if(time)m.currentTime=Math.min(time,m.duration);};m.onpause=m.onseeked=()=>{if(!rangeEdited){$('timeStart').value=m.currentTime.toFixed(1);$('timeEnd').value=m.currentTime.toFixed(1);}};}else m.alt=a.label;$('media').append(m);$('assetTitle').textContent=a.label||'预览';$('assetMeta').textContent=`${labels[active]} · v${a.version}`;$('timeStart').value=$('timeEnd').value=time;$('comment').value='';$('annotationFeedback').textContent='';$('captureTime').hidden=!isVideo;$('timeStart').closest('.time-row').hidden=!isVideo;$('selectionLayer').style.bottom=isVideo?'44px':'0';$('viewerDownload').href=assetURL(a.path);$('viewerDownload').download=a.label||a.path.split('/').pop();$('annotationHint').textContent=isVideo?'可直接播放、拖动进度条；需要局部意见时再开启“框选批注”':'可以直接留下整体意见；需要指出局部时，开启“框选批注”再拖动画框';showDialog('viewer');}
$('toggleAnnotation').onclick=()=>{const on=$('selectionLayer').hidden;$('selectionLayer').hidden=!on;$('toggleAnnotation').setAttribute('aria-pressed',String(on));if(on){const m=$('currentMedia');if(m.tagName==='VIDEO'){m.pause();if(!rangeEdited)$('timeStart').value=$('timeEnd').value=m.currentTime.toFixed(1);}}};
function position(e){const r=$('selectionLayer').getBoundingClientRect();return[Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];}
$('selectionLayer').onpointerdown=e=>{if(e.button!==0)return;const m=$('currentMedia');m.pause?.();drag=position(e);box=null;$('selection').style.display='none';$('selectionLayer').setPointerCapture(e.pointerId);};
$('selectionLayer').onpointermove=e=>{if(!drag)return;const p=position(e);box=[Math.min(drag[0],p[0]),Math.min(drag[1],p[1]),Math.abs(drag[0]-p[0]),Math.abs(drag[1]-p[1])];Object.assign($('selection').style,{display:'block',left:box[0]*100+'%',top:box[1]*100+'%',width:box[2]*100+'%',height:box[3]*100+'%'});};
$('selectionLayer').onpointerup=$('selectionLayer').onpointercancel=()=>{drag=null;if(box&&(box[2]<.005||box[3]<.005)){box=null;$('selection').style.display='none';}};
$('clearBox').onclick=()=>{box=null;$('selection').style.display='none';};$('captureTime').onclick=()=>{rangeEdited=false;const m=$('currentMedia');m.pause();$('timeStart').value=$('timeEnd').value=m.currentTime.toFixed(1);};
$('fullscreenMedia').onclick=()=>operation(async()=>{const m=$('currentMedia');if(m.requestFullscreen)await m.requestFullscreen();else throw Error('此浏览器不支持全屏，请使用视频原生全屏按钮或下载文件查看');});
$('saveAnnotation').onclick=()=>operation(async()=>{const m=$('currentMedia'),isVideo=m.tagName==='VIDEO';if(isVideo&&!m.paused){m.pause();if(!rangeEdited)$('timeStart').value=$('timeEnd').value=m.currentTime.toFixed(1);}const canvas=document.createElement('canvas');canvas.width=isVideo?m.videoWidth:m.naturalWidth;canvas.height=isVideo?m.videoHeight:m.naturalHeight;if(!canvas.width)throw Error('画面尚未载入');const comment=$('comment').value.trim();if(!comment)throw Error('请先填写修改意见');const start=Number($('timeStart').value),end=Number($('timeEnd').value);if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end<start)throw Error('结束时间不能早于开始时间');canvas.getContext('2d').drawImage(m,0,0);const result=await api('capture',{data:canvas.toDataURL('image/png')});let adjusted=box;if(box&&isVideo){const full=m.getBoundingClientRect(),overlay=$('selectionLayer').getBoundingClientRect();adjusted=[box[0],box[1]*overlay.height/full.height,box[2],box[3]*overlay.height/full.height];}await api('annotation',{stage:assetStage,asset:asset.path,screenshot:result.path,screenshotTime:isVideo?m.currentTime:0,version:asset.version,start,end,box:adjusted,comment});$('annotationFeedback').classList.remove('feedback-error');$('annotationFeedback').textContent='批注与截图已保存';$('comment').value='';renderAnnotations();},$('saveAnnotation'));
$('timeStart').oninput=$('timeEnd').oninput=()=>{rangeEdited=true;};
function allThemes(){return[{id:'original',display_name:'原创方向',description:'让内容决定视觉，不套固定模板',original:true},...themes,...(state?.customThemes||[])];}
function themeName(t){return t.display_name||t.zh_name||t.name;}
function themePreview(t){return t.preview||((t.previews||[])[0]?assetURL(t.previews[0]):null);}
function renderSelectedTheme(){const t=allThemes().find(t=>t.id===selectedThemeId);$('selectedThemeName').textContent=t?themeName(t):selectedThemeId;$('selectedThemeDescription').textContent=t?.description||'已选择的视觉参考';const old=$('selectedThemePreview'),src=t&&themePreview(t);const preview=element(src?'img':'div',undefined,src?'':'original-preview');preview.id='selectedThemePreview';if(src){preview.src=src;preview.alt=themeName(t)+'预览';}else preview.append(element('span',t?.custom?'自定义':'自由创作'));old.replaceWith(preview);}
function chooseTheme(id){if(busy)return;selectedThemeId=id;markDirty();renderSelectedTheme();closeDialog('themeDialog');notice('已选择视觉方向，保存需求后生效。');}
function renderThemeGrid(){const query=$('themeSearch').value.trim().toLowerCase(),catalog=allThemes().filter(t=>[themeName(t),t.name,t.description,t.category,...(t.best_for||[])].join(' ').toLowerCase().includes(query));$('themeGrid').replaceChildren();$('themeCount').textContent=`${themes.length} 个预设主题 · ${(state?.customThemes||[]).length} 个自定义主题`;catalog.forEach(t=>{const b=element('button',undefined,'theme-card'+(t.id===selectedThemeId?' selected':''));b.type='button';b.dataset.themeId=t.id;b.setAttribute('aria-pressed',String(t.id===selectedThemeId));b.setAttribute('aria-label','选择 '+themeName(t));const src=themePreview(t);if(src){const im=element('img');im.src=src;im.alt=themeName(t)+'主题预览';im.loading='lazy';b.append(im);}else{const original=element('div',undefined,'original-preview');original.append(element('span',t.original?'自由创作':themeName(t)));b.append(original);}const info=element('span',undefined,'theme-info');info.append(element('strong',themeName(t)),element('small',t.description||t.prompt||''));if(t.name&&t.name!==themeName(t))info.append(element('small',t.name));if(t.palette?.length){const palette=element('span',undefined,'palette');t.palette.forEach(color=>{const sw=element('span',undefined,'swatch');sw.style.backgroundColor=color;sw.title=color;palette.append(sw);});info.append(palette);}info.append(element('span',t.custom?'此项目 · 自定义':t.original?'始终可用':'主题参考','theme-tag'));b.append(info);b.onclick=()=>chooseTheme(t.id);$('themeGrid').append(b);});if(!catalog.length)$('themeGrid').append(element('p','没有匹配的主题，试试其他关键词。','empty'));}
$('chooseTheme').onclick=$('selectedTheme').onclick=()=>{$('themeSearch').value='';renderThemeGrid();showDialog('themeDialog');};$('themeSearch').oninput=renderThemeGrid;
function applyVoicePreviewRate(audio){
  const rate=1+$('voicePreviewRate').valueAsNumber/100;
  audio.defaultPlaybackRate=rate;
  audio.playbackRate=rate;
  for(const key of ['preservesPitch','mozPreservesPitch','webkitPreservesPitch'])if(key in audio)audio[key]=true;
}
function syncVoicePreviewRate(){
  const input=$(provider()+'_rate'),valid=input.value!==''&&input.validity.valid;
  const rate=valid?input.valueAsNumber:0;
  $('voicePreviewRate').value=rate;
  const label=`${rate>0?'+':''}${rate}% · ${(1+rate/100).toFixed(2)}×`;
  $('voicePreviewSpeed').textContent=label;
  $('voicePreviewRate').setAttribute('aria-valuetext',label);
  $('voicePreviewRateHelp').textContent=`与 ${provider()==='azure'?'Azure':'Edge'} 配音语速同步；关闭窗口保留修改，保存需求后生效。`+(valid?'':'需求页语速无效，暂以正常速度试听；调节滑块可改为有效语速。');
  $('voiceList').querySelectorAll('audio').forEach(applyVoicePreviewRate);
}
function changeVoicePreviewRate(value){
  const input=$(provider()+'_rate');
  if(input.value!==String(value)){input.value=value;markDirty();}
  syncVoicePreviewRate();
}
$('voicePreviewRate').oninput=()=>changeVoicePreviewRate($('voicePreviewRate').valueAsNumber);
$('resetVoicePreviewRate').onclick=()=>changeVoicePreviewRate(0);
function renderVoiceList(){
  $('voiceSampleText').textContent=voiceRegistry.sampleText||'';$('voiceFeedback').textContent='';
  const p=provider(),selected=$(p+'_voice').value;
  $('voicePreviewNote').textContent=(p==='azure'?'以下为 Edge 预先录制的音色参考，不是 Azure 实际合成试听。':'播放仓库内的 Edge 预录样本，不发起合成请求。')+'调速只改变本地播放速度，并在浏览器支持时保持音调；实际配音的节奏与停顿可能不同。';
  $('voiceList').querySelectorAll('audio').forEach(audio=>audio.pause());
  $('voiceList').replaceChildren();syncVoicePreviewRate();
  voices.forEach(v=>{
    const card=element('article',undefined,'voice-card'+(v.id===selected?' selected':''));card.dataset.voiceId=v.id;
    const head=element('div',undefined,'voice-card-head'),title=element('div');title.append(element('h3',`${v.name} · ${v.gender}`),element('p',v.description));
    const b=element('button',v.id===selected?'已选择':'选择此音色');b.setAttribute('aria-label','选择音色 '+v.name);
    b.onclick=()=>{$(p+'_voice').value=v.id;renderAudioControls();markDirty();closeDialog('voiceDialog');};head.append(title,b);
    const audio=element('audio');audio.src=v.sampleUrl;audio.controls=true;audio.preload='metadata';audio.setAttribute('aria-label',v.name+'本地试听');
    // Use one shared speed control; native play, pause and seek remain available.
    audio.setAttribute('controlslist','noplaybackrate');applyVoicePreviewRate(audio);
    audio.addEventListener('loadedmetadata',()=>applyVoicePreviewRate(audio));
    audio.addEventListener('play',()=>applyVoicePreviewRate(audio));
    card.append(head,audio);$('voiceList').append(card);
  });
  if(!voices.length)$('voiceList').append(element('p','本地试听目录暂未载入，请刷新页面后重试。','empty'));$('customVoice').value=selected;
}
$('chooseVoice').onclick=()=>{renderVoiceList();showDialog('voiceDialog');};$('selectCustomVoice').onclick=()=>{const v=$('customVoice').value.trim();if(!/^[a-z]{2,3}-[A-Z]{2}-[A-Za-z][A-Za-z0-9]*Neural$/.test(v)){notice('请填写有效的标准 Neural 音色名称',true);return;}$(provider()+'_voice').value=v;renderAudioControls();markDirty();closeDialog('voiceDialog');};
document.addEventListener('play',e=>{if(e.target.matches('audio,video'))document.querySelectorAll('audio,video').forEach(m=>{if(m!==e.target)m.pause();});},true);
function renderCustomThemes(){const existing=state.customThemes||[];$('customThemeList').replaceChildren();if(!existing.length)$('customThemeList').append(element('p','还没有自定义主题。保存后会出现在视觉主题选择器中。','empty'));existing.forEach(t=>{const row=element('div',undefined,'custom-theme-row'),info=element('div');info.append(element('strong',t.name),element('p',t.description||t.prompt));const b=element('button','使用此主题');b.onclick=()=>{if(active!=='requirements'){$('themeSaveFeedback').textContent='主题已保存。请回到需求页，在视觉方向中选择它。';return;}selectedThemeId=t.id;renderSelectedTheme();markDirty();closeDialog('settingsDialog');};const actions=element('div',undefined,'custom-theme-actions');const download=element('a','导出主题包');download.href='/api/themes/export'+suffix+'&id='+encodeURIComponent(t.id);download.download=t.name+'.theme.json';actions.append(b,download);row.append(info,actions);$('customThemeList').append(row);});
  const selected=new Set([...$('customPreviewChoices').querySelectorAll('input:checked')].map(i=>i.value));$('customPreviewChoices').replaceChildren();const seen=new Set();for(const s of Object.values(state.stages))for(const a of s.artifacts){if(!/\.(png|jpe?g|webp)$/i.test(a.path)||seen.has(a.path))continue;seen.add(a.path);const label=element('label',undefined,'preview-choice'),img=element('img');img.src=assetURL(a.path);img.alt=a.label;const input=element('input');input.type='checkbox';input.value=a.path;input.checked=selected.has(a.path);input.onchange=()=>{themeFormDirty=true;};label.append(img,input,document.createTextNode(a.label||'参考图片'));$('customPreviewChoices').append(label);}if(!seen.size)$('customPreviewChoices').append(element('span','尚未导入参考图片','empty'));}
$('settingsButton').onclick=()=>{renderCustomThemes();showDialog('settingsDialog');};for(const id of ['customThemeName','customThemeDescription','customThemePrompt','customThemePalette'])$(id).oninput=()=>{themeFormDirty=true;};
$('createTheme').onclick=()=>operation(async()=>{const palette=$('customThemePalette').value.split(/[,，\s]+/).map(x=>x.trim()).filter(Boolean);await api('theme',{name:$('customThemeName').value.trim(),description:$('customThemeDescription').value.trim(),prompt:$('customThemePrompt').value.trim(),palette,previews:[...$('customPreviewChoices').querySelectorAll('input:checked')].map(i=>i.value)});themeFormDirty=false;$('themeSaveFeedback').classList.remove('feedback-error');$('themeSaveFeedback').textContent='已保存在此项目的主题库';for(const id of ['customThemeName','customThemeDescription','customThemePrompt','customThemePalette'])$(id).value='';$('customPreviewChoices').querySelectorAll('input').forEach(i=>i.checked=false);renderCustomThemes();},$('createTheme'));
for(const id of ['editor','projectTitle','width','height','fps','duration','durationMin','durationMax','styleDirection','qualityNote','bgm_direction'])$(id).addEventListener('input',markDirty);
for(const id of ['azure_rate','edge_rate'])$(id).addEventListener('input',()=>{markDirty();syncVoicePreviewRate();});
for(const field of document.querySelectorAll('input[name="workflowMode"],input[name="soundMode"]'))field.onchange=()=>{markDirty();renderAudioControls();};
$('bgm_mode').onchange=()=>{markDirty();renderBgmControls();};
$('voiceProvider').onchange=()=>{markDirty();renderAudioControls();};$('durationMode').onchange=()=>{markDirty();renderDuration();};$('aspect').onchange=()=>{const dimensions={'16:9':[1920,1080],'9:16':[1080,1920],'1:1':[1080,1080]};if(dimensions[$('aspect').value])[$('width').value,$('height').value]=dimensions[$('aspect').value];if($('aspect').value==='custom')$('advancedSettings').open=true;markDirty();};
$('uploadBgm').onclick=()=>operation(async()=>{const file=$('bgmFile').files[0];if(!file)throw Error('请先选择音乐文件');if(!/\.(wav|mp3|m4a|ogg|flac)$/i.test(file.name))throw Error('请选择 WAV、MP3、M4A、OGG 或 FLAC 音乐');if(!file.size||file.size>32*1024*1024)throw Error('音乐文件需为 32 MiB 以内的非空音频');if(dirty)await saveDraft();const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('无法读取所选音乐文件'));reader.readAsDataURL(file);});await api('bgm-upload',{name:file.name,data});$('bgmFile').value='';render();notice('音乐已导入当前项目。确认需求后，Codex 会安排短样、整曲与混音。');},$('uploadBgm'));
$('uploadMaterial').onclick=()=>operation(async()=>{const file=$('materialFile').files[0];if(!file)throw Error('请先选择参考文件');if(file.size>8000000)throw Error('文件超过 8 MB，请由 Codex 直接放入项目目录');if(dirty)await saveDraft();const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});await api('upload',{name:file.name,data,stage:'requirements'});$('materialFile').value='';render();notice('参考资料已保存，当前需求仍是草稿。确认需求后 Codex 会结合它调研与写稿。');},$('uploadMaterial'));
$('importTheme').onclick=()=>operation(async()=>{const file=$('themeImportFile').files[0];if(!file)throw Error('请先选择导出的 JSON 主题包');if(file.size>10000000)throw Error('主题包超过 10 MB');let pack;try{pack=JSON.parse(await file.text());}catch{throw Error('主题包不是有效 JSON 文件');}await api('theme-import',{pack});$('themeImportFile').value='';renderCustomThemes();$('themeSaveFeedback').textContent='主题包已导入当前项目';},$('importTheme'));
$('help').onclick=()=>showDialog('helpDialog');
window.addEventListener('beforeunload',e=>{if(dirty||themeFormDirty||($('newVideoDialog').open&&$('newVideoName').value.trim())||($('viewer').open&&$('comment').value.trim())){e.preventDefault();e.returnValue='';}});
async function refreshProject(manual=false){if(busy)return;if(manual&&dirty&&!confirm('刷新会放弃当前未保存的修改。确定载入最新项目吗？'))return;const response=await fetch('/api/state'+suffix);if(!response.ok)throw Error('无法读取项目更新');const result=await response.json();token=result.token;if(!manual&&state&&result.project.revision===state.revision)return;if(dirty&&!manual){if(updateNoticeRevision!==result.project.revision){notice('Codex 或另一窗口已更新项目。你的未保存文字仍保留；保存前请复制需要保留的内容，再刷新核对。',true);updateNoticeRevision=result.project.revision;}return;}const following=active===state.active;state=result.project;if(following)active=state.active;render();if(following)history.replaceState({stage:active},'');if(manual)notice('已载入最新项目状态。');}
$('refresh').onclick=()=>operation(async()=>{if(dirty&&!confirm('刷新会放弃当前未保存的修改。确定载入最新项目吗？'))return;const response=await fetch('/api/state'+suffix);if(!response.ok)throw Error('无法读取项目更新');const result=await response.json();state=result.project;token=result.token;render();notice('已载入最新项目状态。');},$('refresh'));
setInterval(()=>{if(state&&!busy&&!document.hidden&&!currentDialog)refreshProject().catch(()=>{$('saved').textContent='连接暂时中断，稍后重试';});},3000);
$('projectPicker').onchange=()=>operation(async()=>{const selected=$('projectPicker').value;if((dirty||themeFormDirty)&&!confirm('有未保存修改。放弃这些修改并切换项目吗？')){$('projectPicker').value=projectKey;return;}try{await api('projects/select',{id:selected});dirty=false;themeFormDirty=false;location.href='/?project='+encodeURIComponent(selected);}catch(e){$('projectPicker').value=projectKey;throw e;}});
$('newVideo').onclick=()=>{if(busy)return;$('newVideoFeedback').textContent='';showDialog('newVideoDialog');$('newVideoName').focus();};
$('createVideo').onclick=()=>operation(async()=>{const title=$('newVideoName').value.trim();if(!title)throw Error('请先给新视频起个名字');if((dirty||themeFormDirty)&&!confirm('当前项目有未保存修改。放弃这些修改并创建新视频吗？已保存的旧项目会保留。'))return;const result=await api('projects/create',{title});dirty=false;themeFormDirty=false;$('newVideoName').value='';location.href='/?project='+encodeURIComponent(result.created.id);},$('createVideo'));

async function init(){try{const [result,projects,themeData,voiceData]=await Promise.all([fetch('/api/state'+suffix).then(r=>{if(!r.ok)throw Error('无法读取项目');return r.json();}),fetch('/api/projects').then(r=>r.json()),fetch('/presets/themes.json').then(r=>r.ok?r.json():null).catch(()=>null),fetch('/presets/voices.json').then(r=>r.ok?r.json():null).catch(()=>null)]);state=result.project;token=result.token;workspacePath=result.workspace||'';active=stages.includes(state.active)?state.active:'narration';themes=themeData?.themes||[];voiceRegistry=voiceData||{};voices=voiceRegistry.voices||[];projects.projects.forEach(p=>{const option=element('option',p.title);option.value=p.id;$('projectPicker').append(option);});$('projectPicker').value=projectKey;history.replaceState({stage:active},'');render();if(!themeData||!voiceData)notice('部分本地预设目录未载入。项目可以编辑；主题与音色目录准备好后请刷新页面。',true);}catch(e){notice('无法连接本地工作台：'+e.message,true);}}
init();

// Credentials never enter workflow payloads, persisted browser storage, or history.
let credentialBusy=false, credentialStatus=null;
function clearCredentialInput(){$('azureKey').value='';$('azureRegion').value='';$('credentialEditor').hidden=true;}
function credentialButtons(){
  $('editCredentials').disabled=credentialBusy||!credentialStatus?.available;
  $('deleteCredentials').disabled=credentialBusy||!credentialStatus?.saved;
  $('saveCredentials').disabled=credentialBusy||!credentialStatus?.available;
  $('azureKey').disabled=$('azureRegion').disabled=credentialBusy;
}
function displayCredentialStatus(value){credentialStatus=value;$('credentialStatus').textContent=
  (value.configured?'已配置 · '+value.region+' · 来源：'+(value.source==='environment'?'环境变量（优先）':'Windows 凭据管理器'):'尚未配置')+
  (value.available?'':'。当前系统不支持安全保存；可由你自行配置两个环境变量。')+
  (value.saved&&value.source==='environment'?'；凭据管理器中另有已保存记录':'');credentialButtons();}
async function credentialRequest(action,data={}){
  let body=JSON.stringify(data);
  try{const response=await fetch('/api/credentials/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':token},body,cache:'no-store',credentials:'same-origin'});const result=await response.json();if(!response.ok)throw Error(result.error||'凭据操作失败');return result;}finally{body=null;}
}
async function credentialOperation(action,data={}){
  if(credentialBusy)return;
  credentialBusy=true;credentialButtons();$('credentialFeedback').textContent='';
  try{displayCredentialStatus(await credentialRequest(action,data));if(action!=='status'){clearCredentialInput();$('credentialFeedback').textContent=action==='save'?'已保存，密钥已隐藏。保存不代表 Azure 认证已验证。':'已删除凭据管理器中的记录。';}}
  catch(e){$('credentialFeedback').textContent=e.message;if(action==='status'){credentialStatus=null;$('credentialStatus').textContent='无法确认凭据状态，请检查本机安全存储。';}}
  finally{if(data.key)data.key='';credentialBusy=false;credentialButtons();}
}
$('settingsAzureCredentials').onclick=$('openAzureCredentials').onclick=()=>{if($('settingsDialog').open){if(!closeDialog('settingsDialog',true))return;history.replaceState({stage:active},'');}clearCredentialInput();credentialStatus=null;credentialButtons();showDialog('credentialDialog');credentialOperation('status');};
$('editCredentials').onclick=()=>{clearCredentialInput();$('credentialEditor').hidden=false;$('azureRegion').value=credentialStatus?.region||'';$('azureKey').focus();};
$('cancelCredentials').onclick=clearCredentialInput;
$('saveCredentials').onclick=()=>{if(credentialBusy)return;const data={key:$('azureKey').value,region:$('azureRegion').value.trim()};$('azureKey').value='';credentialOperation('save',data);};
$('deleteCredentials').onclick=()=>{if(!credentialBusy&&confirm('删除本机凭据管理器中所有项目共用的 Azure 凭据？环境变量不会被删除。')){clearCredentialInput();credentialOperation('delete');}};
$('credentialDialog').addEventListener('close',clearCredentialInput);
window.addEventListener('pagehide',clearCredentialInput);
window.addEventListener('pageshow',clearCredentialInput);
